export const CHANGE_SERACH_FIELD = 'home/CHANGE_SEARCH_FIELD'

export const REQUEST_CATS_PENDING = 'hoem/REQUEST_CATS_PENDING'
export const REQUEST_CATS_SUCCESS = 'hoem/REQUEST_CATS_SUCCESS'
export const REQUEST_CATS_FAILED = 'hoem/REQUEST_CATS_FAILED'